"Mutation root"
type Mutation {
  createTask(task: TaskModifyInput!): Task
  deleteTask(id: Int!, version: Int!): Task
  dragTask(dragTask: DragTaskInput!): Task
  updateTask(id: Int!, task: TaskModifyInput!, version: Int!): Task
}

"Query root"
type Query {
  getTaskById(id: Int!): Task
  getTasks(
    description: String
    limit: Int = 20
    offset: Int = 0
  ): [TasksByStatusDTO]
}

type Task {
  createdBy: String
  description: String!
  id: BigInteger
  taskOrder: Int
  taskPriority: TaskPriority!
  taskStatus: TaskStatus!
  title: String!
  updatedBy: String
  users: [User]
  version: Int
}

type TasksByStatusDTO {
  status: TaskStatus
  tasks: [Task]
}

type User {
  email: String!
  fullName: String!
  id: BigInteger
  image: [Int!]
  password: String
  tasks: [Task]
  token: String
}

enum TaskPriority {
  HIGH
  LOW
  MED
}

enum TaskStatus {
  DONE
  IN_PROGRESS
  TO_DO
}

input DragTaskInput {
  taskId: BigInteger!
  taskOrder: Int!
  taskStatus: TaskStatus!
  taskVersion: Int!
}

input TaskModifyInput {
  createdBy: String
  description: String!
  id: BigInteger
  taskOrder: Int
  taskPriority: TaskPriority!
  taskStatus: TaskStatus!
  title: String!
  updatedBy: String
  users: [UserInputInput]
}

input UserInputInput {
  email: String
  fullName: String
  id: BigInteger
  image: [Int!]
  token: String
}
