input UserInput {
  id!: Int
  fullName: String
  email: String
  token: String
  image: String
  password: String
}

input TaskInput {
  id: Long!
  title: String!
  description: String!
  taskStatus: String!
  taskPriority: String!
  version: Int!
  taskOrder: Int!
  users: [UserInput!]!
}


type User {
  id: Long!
  fullName: String!
  email: String!
  password: String
}

type Task {
  id: Int!
  title: String!
  description: String!
  taskStatus: String!
  taskPriority: String!
  version: Int!
  taskOrder: Int!
  users: [User!]!
}

type OptionalTask {
  id: Int
  title: String
  description: String
  taskStatus: String
  taskPriority: String
  version: Int
  users: [User!]!
}

type TasksByStatus {
  status: String;
  tasks: [Task!]!
}

type Query {
  getTaskById(id: Int!): Task!
  getTasks(limit: Int!, offset: Int!, description: String): [TasksByStatus!]!
}

type Mutation {
  createTask(task: TaskInput!): OptionalTask
  updateTask(id: Int!, task: TaskInput!): OptionalTask
  deleteTask(id: Int!, version: Int!): OptionalTask
  dragTask(taskId: Int!, taskStatus: String!, taskOrder: Int!, taskVersion: Int): OptionalTask
}
